version: '3.3'
services:
  web:
    build: .
    container_name: dienstplan
    depends_on: 
      - db
    volumes: 
      - ./src:/var/www/html/
      - ./php.ini:/usr/local/etc/php/conf.d/30-custom.ini
    ports:
      - 80:80
  db: 
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - 3306:3306

